name       : ibus-m17n
version    : 1.3.4
release    : 3
source     :
    - https://github.com/ibus/ibus-m17n/archive/1.3.4.tar.gz : 33b4f51337fb633a1d5c476a7ec459670a51285f8658d74a5db98ed3c8c706f5
license    : GPL-2.0
component  : desktop.library
summary    : M17N engine for IBus
description: |
    M17N engine for IBus
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(m17n-core)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |-
    %make_install
